Repository Azure/azure-sdk, pull requests merged in 2019-11, with the labels that each got.

#645 Add EventSource guidance
  docs/dotnet/implementation.md
Labels: architecture

#773 Update section on JS/TS versioning
  docs/policies/releases.md
Labels: Client, Typescript

#721 change guidelines on internal structs
  docs/clang/design.md
Labels: C99

#722 Object model fixes
  docs/clang/design.md
Labels: C99

#740 Replace ResponseFailedException with RequestFailedException
  docs/dotnet/introduction.md
Labels: .NET
