Repository Azure/azure-sdk, pull requests merged in 2019-04, with the labels that each got.

#249 Proposed changes/clarifications of logging.mk
  docs/design/Logging.mdk
Labels: architecture

#287 Update of terminology (SDK to client library) in the review process doc.
  README.md
  docs/ReviewProcess.md
Labels: architecture

#285 Parameter Validation requirements
  docs/design/DesignGuidelines.mdk
  docs/design/ParameterValidation.mdk
Labels: architecture

#302 Update per review feedback from Bryan
  docs/design/python/DesignGuidelines.mdk
Labels: architecture

#290 Added default policies document
  docs/design/DefaultPolicies.mdk
  docs/design/DesignGuidelines.mdk
Labels: architecture

#296 Start of guidelines for preview and GA releases
  docs/engineering-system/releases.md
Labels: EngSys, architecture

#310 Updated SDK Component to Client library and adjusted some grammar
  docs/design/Cancellations.mdk
  docs/design/Dependencies.mdk
  docs/design/OpenSource.mdk
  docs/design/README.md
  docs/design/Requirements.mdk
Labels: architecture

#314 General Guidelines: Terminology
  docs/design/DesignGuidelines.mdk
  docs/design/Introduction.mdk
  docs/design/Terminology.mdk
Labels: architecture

#318 General Guidelines: Versioning
  docs/design/DesignGuidelines.mdk
  docs/design/Versioning.mdk
Labels: architecture

#307 General Guidelines: Documentation
  docs/design/DesignGuidelines.mdk
  docs/design/Documentation.mdk
Labels: architecture

#305 General Guidelines: Proxy Support
  docs/design/DesignGuidelines.mdk
  docs/design/Proxy.mdk
Labels: architecture

#327 [Azure Messaging .NET Clients] ReadMe Repository Locations
  README.md
Labels: .NET, Client

#329 Added distributed tracing guidelines
  docs/design/DesignGuidelines.mdk
  docs/design/DistributedTracing.mdk
Labels: architecture
