Repository Azure/azure-sdk, pull requests merged in 2019-12, with the labels that each got.

#810 add guideline on using secure zeroing functions
  docs/clang/implementation.md
Labels: C99

#809 Don't use Weverything.
  docs/clang/implementation.md
Labels: C99

#808 formatting section changes, no yoda anymore
  docs/clang/implementation.md
Labels: C99

#716 variable initialization revision
  docs/clang/implementation.md
Labels: C99

#821 December Release Notes for .NET
  releases/2019-12/2019-12-dotnet.md
Labels: Client, Docs, Event Hubs

#822 Update 2019-12-java.md
  releases/2019-12/2019-12-java.md
Labels: AzConfig

#794 no runtime configuration for c.
  docs/clang/implementation.md
Labels: C99, architecture

#856 Release Package List - Adding Event Hubs: Event Processor
  _data/releases/latest/dotnet-packages.csv
Labels: Client, Docs

#860 Release Package List - Tweak Event Hubs Names
  _data/releases/latest/dotnet-packages.csv
Labels: Client, Docs, Event Hubs
