Repository Azure/azure-sdk, pull requests merged in 2019-10, with the labels that each got.

#681 .NET Release for Preview 4: Updating Event Hubs Release Notes
  releases/2019-10-11/2019-10-11-dotnet-preview4.md
Labels: Client, Event Hubs

#683 Event Hubs: Update reference example
  releases/2019-10-11/2019-10-11-dotnet-preview4.md
Labels: Client, Event Hubs

#700 clarify interdependency in unified pipelines
  docs/policies/releases.md
Labels: EngSys

#646 (#638) Added requirements for etag handling
  docs/general/design.md
Labels: architecture

#703 Fix spelling of 'dependencies'
  docs/policies/releases.md
Labels: EngSys

#648 Add guidelines on enum-like structs for .NET
  docs/dotnet/implementation.md
  docs/dotnet/introduction.md
Labels: architecture

#664 Added guidance on naming of model types
  docs/general/design.md
Labels: architecture

#718 clang format use file
  docs/clang/implementation.md
Labels: C99

#749 .NET Release for November: Event Hubs Release Notes
  releases/2019-11/2019-11-dotnet.md
Labels: .NET, Client, Event Hubs

#748 add an example for doxygen usage in cmake
  docs/clang/documentation.md
Labels: C99

#758 App Config Readme, chagnelog, samples link update
  releases/2019-11/2019-11-java.md
Labels: AzConfig
