Repository Azure/azure-sdk, pull requests merged in 2020-10, with the labels that each got.

#1872 Change header value for changelog sub-headings from 4 to 3 to be consistent.
  releases/2020-09/c.md
Labels: C99, auto-merge

#1887 Add Python Service Bus 7.0.0b7 (October) release notes.
  releases/2020-10/python.md
Labels: Client, Service Bus

#1893 add TA 5.1.0b2 release notes
  releases/2020-10/python.md
Labels: auto-merge

#1907 Add metrics advisor new package to package index
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1904 Identity and Key Vault 2020-10 release notes
  releases/2020-10/python.md
Labels: auto-merge

#1906 [TA] .NET changelog
  releases/2020-09/dotnet.md
  releases/2020-10/dotnet.md
Labels: auto-merge

#1877 Update package index with latest published versions
  _data/releases/latest/c-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1919 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1931 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1936 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1928 [.NET] Added remaining October release notes
  releases/2020-10/dotnet.md
Labels: .NET

#1943 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1927 Add links to the C and C++ documentation
  README.md
Labels: C++, C99

#1938 Add guidance to use lower case for our anchor tags in links
  docs/policies/README-TEMPLATE.md
Labels: auto-merge

#1944 Review view from doc links
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
  _data/sidebars/dotnet_sidebar.yml
  _includes/releases/pkgrow.md
  _includes/releases/variables/android.md
  _includes/releases/variables/c.md
  _includes/releases/variables/cpp.md
  _includes/releases/variables/dotnet.md
  _includes/releases/variables/ios.md
  _includes/releases/variables/java.md
  _includes/releases/variables/js.md
  _includes/releases/variables/python.md
  docs/clang/design.md
  docs/clang/implementation.md
  docs/cpp/design.md
  docs/cpp/implementation.md
  docs/policies/README-TEMPLATE.md
  releases/2020-09/dotnet.md
Labels: auto-merge

#1946 Add release version notes for C++
  docs/policies/releases.md
Labels: C++, auto-merge

#1950 Add note about immutable release tags
  docs/policies/repobranching.md
Labels: auto-merge

#1947 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1957 update c and cpp links from refs
  _includes/refs.md
  releases/2020-09/cpp.md
  releases/2020-10/cpp.md
Labels: Azure.Core, C++, C99

#1963 Add link guidance to use https instead of http
  docs/policies/README-TEMPLATE.md
Labels: auto-merge

#1960 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1967 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1971 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#1976 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1979 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge
