Repository Azure/azure-sdk, pull requests merged in 2020-03, with the labels that each got.

#1078 Update TA CHANGELOG for March 2020
  releases/2020-03/java.md
Labels: TextAnalytics

#1070 Add event hubs into March 2020 release notes
  releases/2020-03/python.md
Labels: Event Hubs

#1125 Spelling corrections
  docs/cpp/design.md
  docs/cpp/implementation.md
Labels: CXX

#1058 (#1043) Updates to guidelines from arch.board meeting
  docs/general/design.md
  docs/general/implementation.md
Labels: architecture

#1144 Update Platform List
  docs/cpp/implementation.md
Labels: CXX, Client, Docs
