Repository Azure/azure-sdk, pull requests merged in 2020-08, with the labels that each got.

#1617 only search first column
  js/customscripts.js
Labels: auto-merge

#1622 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1626 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#1615 Update language to refer to new release tag formatting
  docs/policies/releases.md
Labels: EngSys

#1628 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1587 adding workarounds and reasoning for link guidance update
  docs/policies/README-TEMPLATE.md
Labels: EngSys

#1633 [August Release Notes] Event Hubs
  releases/2020-08/dotnet.md
Labels: Docs, Event Hubs

#1602 Draft post for EngSys 2020-08-11
  _posts/2020-08-11-packaging-tools-and-repositories.md
  images/posts/go-package-structure.PNG
  images/posts/swift-package-structure.png
Labels: EngSys

#1636 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1648 Add Python Service Bus 7.0.0b5 (Track 2, preview 5, August) release notes.
  releases/2020-08/python.md
Labels: Client, Service Bus

#1658 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1670 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1675 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1689 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1695 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1712 Reltempupdates
  eng/scripts/release-template/index.md
Labels: auto-merge

#1711 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1715 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#1724 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1722 [.NET] Added FormRecognizer 3.0.0 to 2020/09 release notes
  releases/2020-09/dotnet.md
Labels: FormRecognizer

#1729 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1732 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1610 Add example of extensible enum constants
  docs/dotnet/implementation.md
Labels: .NET

#1735 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge
