Repository Azure/azure-sdk, pull requests merged in 2020-12, with the labels that each got.

#2079 [Text Analytics] Add release notes for November
  releases/2020-11/js.md
Labels: auto-merge

#2080 [Text Analytics] Edit notes
  releases/2020-11/js.md
Labels: auto-merge

#2003 Add more clarity to LRO guidelines regarding exception behavior
  docs/dotnet/introduction.md
Labels: ArchBoard Guidelines

#2082 [.NET] Updated 2020/11 release notes with latest releases
  releases/2020-11/dotnet.md
Labels: .NET

#2112 MQ Guidelines Initiative: JS/TS TODOs
  docs/typescript/design.md
  docs/typescript/implementation.md
Labels: ArchBoard Guidelines, MQ

#2062 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2103 MQ Guidelines Initiative: Python TODOs
  docs/python/design.md
Labels: ArchBoard Guidelines, MQ

#2095 MQ Guidelines Initiative: .NET TODOs
  css/customstyles.css
  docs/dotnet/implementation.md
  docs/dotnet/introduction.md
Labels: ArchBoard Guidelines, MQ

#2134 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2143 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1249 Ban Const members of structs
  docs/clang/design.md
Labels: C99

#1733 clang, prohibit first level const in function signatures
  docs/clang/design.md
Labels: C99

#2153 Add deputy architects to CODEOWNERS file.
  .github/CODEOWNERS
Labels: auto-merge

#2149 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1918 Update opensource.md
  docs/policies/opensource.md
Labels: auto-merge

#2152 Fix extensible enum example
  docs/cpp/design.md
Labels: ArchBoard Guidelines, C++

#2124 Updating Java Design Guidelines to match latest spec
  _data/sidebars/general_sidebar.yml
  docs/java/design.md
  docs/java/documentation.md
  docs/java/implementation.md
  docs/java/introduction.md
  docs/java/refs.md
Labels: ArchBoard Guidelines

#2175 add twitter link to ignore list. standard GET are being rejected
  _data/releases/latest/js-packages.csv
  docs/python/design.md
  eng/ignore-links.txt
Labels: auto-merge

#2167 Synapse 1.0.0-beta.1 release
  _data/releases/latest/java-packages.csv
  releases/2020-12/java.md
Labels: auto-merge

#2174 Remove 'will replace' notes for SB
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2176 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2178 Refactor the C++ guidelines
  .gitignore
  _data/sidebars/general_sidebar.yml
  docs/cpp/design.md
  docs/cpp/documentation.md
  docs/cpp/implementation.md
  docs/cpp/introduction.md
Labels: ArchBoard Guidelines, C++

#2180 Refactor the Embedded C guidelines to follow new guideline structure.
  README.md
  _data/sidebars/general_sidebar.yml
  _data/topnav.yml
  _includes/refs.md
  docs/clang/design.md
  docs/clang/documentation.md
  docs/clang/implementation.md
  docs/clang/introduction.md
Labels: ArchBoard Guidelines, C99
