Repository Azure/azure-sdk, pull requests merged in 2020-07, with the labels that each got.

#1512 [July Release Notes for .NET] Event Hubs
  releases/2020-07/dotnet.md
Labels: Docs, Event Hubs

#1517 Add Python Service Bus 7.0.0b4 (Track 2, preview 4, July) release notes.
  releases/2020-07/python.md
Labels: Client, Service Bus

#1523 azure-identity 2020-07 release notes
  releases/2020-07/python.md
Labels: Azure.Identity

#1522 python eventhubs release notes for July
  releases/2020-07/python.md
Labels: Client, Event Hubs

#1513 [.NET] Updating Form Recognizer Release Notes (2020-07)
  releases/2020-07/dotnet.md
Labels: FormRecognizer
