Repository Azure/azure-sdk, pull requests merged in 2020-04, with the labels that each got.

#1177 [April Release Notes] Event Hubs Client
  releases/2020-04/dotnet.md
Labels: Docs

#1178 [April Release Notes] Event Hubs Installation Instructions
  releases/2020-04/dotnet.md
Labels: Docs

#1186 Add servicebus to python april releases
  releases/2020-04/python.md
Labels: Client, Service Bus

#1188 [Event Hubs] Add Event Hubs to Release Notes of 2020/04
  releases/2020-04/python.md
Labels: Event Hubs

#1206 Updated AppConfig and Text Analytics release note
  releases/2020-04/java.md
Labels: AzConfig, Client, TextAnalytics

#1238 Correcting feed for python
  _includes/releases/all/python.md
Labels: EngSys

#1216 Adding notes for all packages list
  _data/allpackages/dotnet-packages.csv
  _data/allpackages/java-packages.csv
  _data/allpackages/js-packages.csv
  _data/allpackages/python-packages.csv
Labels: Docs

#1263 Release notes (.NET): Azure.AI.FormRecognizer 1.0.0-preview1
  _data/releases/latest/dotnet-packages.csv
  releases/2020-04/dotnet.md
Labels: FormRecognizer

#1235 Review samples and use github issues
  docs/policies/reviewprocess.md
Labels: Docs, EngSys

#1273 Adding form recognizer to that latest releases
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: Docs
