Repository Azure/azure-sdk, pull requests merged in 2020-05, with the labels that each got.

#1286 [May Release Notes] Event Hubs
  releases/2020-05/dotnet.md
Labels: Docs

#1288 2020-05 Python Identity notes
  releases/2020-05/python.md
Labels: Azure.Identity

#1296 Add service bus 7.0.0b2 release info to python.md changelist for 2020-05
  releases/2020-05/python.md
Labels: Client, Service Bus

#1297 [Event Hubs] 2020/05 release notes
  releases/2020-05/python.md
Labels: Client, Event Hubs

#1308 Adding .NET Form Recognizer 1.0.0-preview2 release notes
  releases/2020-05/dotnet.md
Labels: FormRecognizer

#1314 Adding ASP.NET extensions to the .NET releases
  _data/releases/latest/dotnet-packages.csv
Labels: Docs

#1313 Update Release Notes for Service Bus preview 2
  releases/2020-05/java.md
Labels: Service Bus

#1155 Various updates to Java guidelines
  _data/sidebars/java_sidebar.yml
  docs/java/approved_dependencies.md
  docs/java/design.md
  docs/java/documentation.md
  docs/java/implementation.md
  docs/java/spring.md
Labels: Java, architecture
