Repository Azure/azure-sdk, pull requests merged in 2020-11, with the labels that each got.

#1980 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1989 Update java key vault names
  _data/releases/latest/android-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1993 More CSV text updates
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#1990 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2002 [Release Notes] Event Hubs: November
  releases/2020-11/dotnet.md
Labels: Docs

#2007 Add Python Servicebus release notes for 7.0.0b8 (November sprint)
  releases/2020-11/python.md
Labels: Client, Service Bus, auto-merge

#2008 Update package index with latest published versions
  _data/releases/latest/c-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2020 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2026 Update python.md
  releases/2020-11/python.md
Labels: auto-merge

#2028 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2023 avoid expanding the preview buttons and wrap them
  _includes/releases/pkgbadge.md
  css/customstyles.css
Labels: Docs

#2033 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2030 [.NET] Adding 2020/Nov release notes
  releases/2020-11/dotnet.md
Labels: .NET, auto-merge

#2039 python Form Recognizer release notes for Nov
  releases/2020-11/python.md
Labels: auto-merge

#2034 [C/C++] Adding 2020/Nov release notes
  releases/2020-11/c.md
  releases/2020-11/cpp.md
Labels: C++

#2041 [ts] Remove specific node numbers from docs
  docs/typescript/design.md
Labels: Typescript

#2037 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2046 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2042 Make table to wrap words from all content by words
  _includes/releases/nav.md
  _includes/releases/pkgrow.md
  _includes/releases/pkgtable.md
  css/customstyles.css
Labels: Docs

#2053 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2054 Updating Speech with Type and Service
  _data/releases/latest/dotnet-packages.csv
Labels: auto-merge

#2057 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2061 [python, form recognizer] fix changelog link to point to release
  releases/2020-11/python.md
Labels: auto-merge

#2059 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2069 Add new release folder structure
  _data/sidebars/releases_sidebar.yml
Labels: auto-merge
