Repository Azure/azure-sdk, pull requests merged in 2020-09, with the labels that each got.

#1740 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1747 Add Anomaly detector to Java packages
  _data/releases/latest/java-packages.csv
Labels: Client, Docs, Java, auto-merge

#1751 [Sepember Release Notes] Event Hubs
  releases/2020-09/dotnet.md
Labels: Docs

#1745 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1756 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1759 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1761 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1770 Add Python Event Hubs CheckpointStoreBlob 1.1.1 (September) release notes
  releases/2020-09/python.md
Labels: Client, Event Hubs

#1766 Add Python Event Hubs 5.2.0 (September) release notes.
  releases/2020-09/python.md
Labels: Client, Event Hubs

#1749 Add Azure Tables to release notes
  releases/2020-09/index.md
Labels: auto-merge

#1773 Identity and Key Vault Administration notes
  releases/2020-09/python.md
Labels: Python

#1776 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1748 Update working with forks link
  docs/policies/repobranching.md
Labels: auto-merge

#1785 Add Python Service Bus 7.0.0b6 (September) release notes.
  releases/2020-09/python.md
Labels: Client, Service Bus

#1786 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1793 Updated Java release notes with Key Vault info.
  releases/2020-09/java.md
Labels: Client, Java

#1791 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1798 Update dotnet-packages.csv
  _data/releases/latest/dotnet-packages.csv
Labels: auto-merge

#1809 [.NET] Update 2020-09 release notes with missing packages
  releases/2020-09/dotnet.md
Labels: .NET

#1812 Update Identity Release notes Sep 2020
  releases/2020-09/java.md
Labels: auto-merge

#1811 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1815 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1817 Release templates for Embedded C and C++
  eng/scripts/release-template/c.md
  eng/scripts/release-template/cpp.md
  eng/scripts/release-template/index.md
Labels: C++, C99

#1731 Add C99 release guidelines
  docs/policies/releases.md
Labels: C99

#1827 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#1831 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1832 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1476 [cpp] Add CreateFromConnectionString guidelines.
  docs/cpp/design.md
Labels: C++

#1836 Text Analytics September Release note, OutOfBand
  releases/2020-09/java.md
Labels: TextAnalytics

#1837 Update package index with latest published versions
  _data/releases/latest/c-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1840 Update java-packages.csv to include Digital Twins
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#1842 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1847 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1850 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1834 Cpp design docs
  docs/cpp/design.md
  docs/cpp/implementation.md
  docs/tables/registered_namespaces.md
Labels: C++

#1818 September release notes
  eng/scripts/release-template/c.md
  eng/scripts/release-template/cpp.md
  releases/2020-09/c.md
  releases/2020-09/cpp.md
  releases/2020-09/index.md
Labels: C++, C99

#1849 Update python packages.csv for newly onboarded track 2 packages
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1477 [cpp] Add 'extensible enum' guidelines
  docs/cpp/design.md
Labels: C++

#1866 [Octoboer Release Notes] Event Hubs
  releases/2020-10/dotnet.md
Labels: Docs

#1855 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#1874 [Release Notes] Event Hubs, Part II
  releases/2020-10/dotnet.md
Labels: Docs

#1876 Update dotnet-packages.csv
  _data/releases/latest/dotnet-packages.csv
Labels: auto-merge
