Repository Azure/azure-sdk, pull requests merged in 2020-01, with the labels that each got.

#813 [JS/TS] Add some retry guidelines
  docs/typescript/design.md
Labels: Typescript, architecture

#924 Add text analytics package
  _data/releases/latest/js-packages.csv
  releases/2020-01/2020-01-js.md
Labels: Client

#932 January Release Notes: Addition of Event Hubs information
  releases/2020-01/dotnet.md
Labels: Client, Docs

#948 Rename examples
  docs/clang/design.md
  docs/clang/documentation.md
  docs/clang/implementation.md
Labels: C99

#961 Add notes about pipeline structure.
  _data/sidebars/android_sidebar.yml
  _data/sidebars/clang_sidebar.yml
  _data/sidebars/cpp_sidebar.yml
  _data/sidebars/dotnet_sidebar.yml
  _data/sidebars/general_sidebar.yml
  _data/sidebars/golang_sidebar.yml
  _data/sidebars/home_sidebar.yml
  _data/sidebars/ios_sidebar.yml
  _data/sidebars/java_sidebar.yml
  _data/sidebars/js_sidebar.yml
  _data/sidebars/python_sidebar.yml
  docs/policies/pipelines.md
Labels: EngSys
