Repository Azure/azure-sdk, pull requests merged in 2021-03, with the labels that each got.

#2486 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2488 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2497 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2504 update broken links
  releases/2020-04/dotnet.md
Labels: Docs

#2508 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2515 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2521 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2528 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2536 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2533 Update NET verbs table to be like all other langs and intro
  _data/tables/net_standard_verbs.yaml
  _includes/tables/standard_verbs_row.html
  _includes/tables/standard_verbs_template.html
  css/customstyles.css
  docs/dotnet/introduction.md
Labels: GitHub IO Site

#2545 Update package index with latest published versions
  _data/releases/latest/c-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2558 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2564 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2568 Change Iot to IoT
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
  _includes/tables/data_namespaces_pascal_case.md
  docs/clang/design.md
  docs/cpp/introduction.md
  docs/dotnet/introduction.md
  releases/2021-01/index.md
Labels: auto-merge

#2567 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2573 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2579 changelog for c and cpp
  releases/2021-03/c.md
  releases/2021-03/cpp.md
Labels: Azure.Core, Client

#2580 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2586 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2591 Merge March Release Notes with what was in Blog
  releases/2021-03/index.md
Labels: auto-merge

#2600 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2602 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2608 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2614 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2616 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2629 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2637 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2639 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/c-packages.csv
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge
