Repository Azure/azure-sdk, pull requests merged in 2021-04, with the labels that each got.

#2647 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2656 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2663 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2668 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2671 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2681 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2689 Add key Vault cpp release
  _data/releases/latest/cpp-packages.csv
Labels: Client, KeyVault

#2682 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2695 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2700 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2696 [UX] Update android standard verb names table
  _data/tables/android_standard_verbs.yaml
  _includes/tables/standard_verbs_row.html
  docs/android/design.md
Labels: Docs, GitHub IO Site

#2702 changelog from cpp - APR Release
  releases/2021-04/c.md
  releases/2021-04/cpp.md
  releases/2021-04/index.md
Labels: C++, Client

#2701 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2705 Remove extra new line in release changelog from cpp for April Release
  releases/2021-04/cpp.md
Labels: C++, Client

#2707 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#2709 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2712 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2715 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2720 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2721 Update Iot to IoT
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
  releases/2019-10-11/2019-10-11-js-preview4.md
  releases/2019-10-11/2019-10-11-python-preview4.md
  releases/2019-11/2019-11-python.md
  releases/2020-01/python.md
  releases/2020-04/python.md
  releases/2021-03/dotnet.md
  releases/2021-03/java.md
  releases/2021-04/dotnet.md
Labels: auto-merge

#2716 Java mgmt, update package csv for newly release T2 SDKs
  _data/releases/latest/java-packages.csv
Labels: Mgmt

#2725 Fix table display on mobile
  _data/releases/latest/dotnet-packages.csv
  _includes/releases/pkgtable.md
  releases/2021-03/dotnet.md
  releases/2021-04/dotnet.md
Labels: auto-merge

#2722 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2726 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#2727 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2728 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2729 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2735 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2736 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2739 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2740 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2743 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2746 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2747 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2748 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2751 update for newly release Java mgmt packages in csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#2749 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2753 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2755 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2756 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2776 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2778 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2780 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2786 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2789 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2790 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#2792 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2793 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2795 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
Labels: auto-merge
