Repository Azure/azure-sdk, pull requests merged in 2021-01, with the labels that each got.

#2182 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#2186 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2190 Update guidelines for constants
  docs/cpp/introduction.md
Labels: ArchBoard Guidelines, C++, auto-merge

#2198 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2202 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2204 Adding C++ identity to latest release info
  _data/releases/latest/cpp-packages.csv
Labels: Azure.Identity

#2209 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2222 adding missing permlink for sidebar
  releases/2020-12/index.md
Labels: Docs

#2216 Unify lang releases md
  _includes/releases/languages.md
  index.md
  releases/latest/all/index.md
  releases/latest/index.md
  releases/latest/mgmt/index.md
Labels: Docs

#2230 Release notes for Azure.Core helpers
  releases/2021-01/dotnet.md
Labels: auto-merge

#2235 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2237 [text analytics] [form recognizer] release notes for patch release
  releases/2021-01/python.md
Labels: auto-merge

#2239 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#2245 service bus release note update
  releases/2021-01/python.md
Labels: auto-merge

#2251 Update python.md
  releases/2021-01/python.md
Labels: auto-merge

#2240 January release highlights for JavaScript & TypeScript
  releases/2021-01/js.md
Labels: auto-merge

#2257 jan2021 changelog for c and c++
  releases/2021-01/c.md
  releases/2021-01/cpp.md
  releases/2021-01/index.md
Labels: C++, C99

#2264 Update install instructions for beta package
  releases/2021-01/python.md
Labels: auto-merge

#2269 General highlights, at least from the JS perspective
  releases/2021-01/index.md
Labels: auto-merge

#2271 [.NET] 2021/01 release notes
  releases/2021-01/dotnet.md
Labels: .NET

#2267 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2276 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2283 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2285 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2287 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2288 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2308 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#2132 Template for Migration guide
  docs/policies/migration-guide-template.md
  docs/policies/releases.md
Labels: auto-merge
