Repository Azure/azure-sdk, pull requests merged in 2022-01, with the labels that each got.

#3704 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3725 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3729 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
Labels: auto-merge

#3730 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3732 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3733 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3736 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3737 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3739 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3741 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3747 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3748 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3754 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3756 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3758 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3763 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3764 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3769 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3782 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3783 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3787 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3711 java mgmt, update csv for new releases
  _data/releases/latest/java-packages.csv
Labels: Mgmt, Java

#3789 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3803 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3805 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#3810 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3815 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3818 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3821 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
Labels: auto-merge

#3822 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3824 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3829 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3830 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3837 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#3838 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3845 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3846 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#3848 use `search` as query to load field
  _includes/releases/header.md
  css/customstyles.css
  images/share.png
  js/customscripts.js
Labels: GitHub IO Site
