Repository Azure/azure-sdk, pull requests merged in 2022-06, with the labels that each got.

#4358 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4376 [CODEOWNERS] Update leads + languages
  .github/CODEOWNERS
Labels: EngSys, Client

#4378 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#4380 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#4381 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4391 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#4392 Update package index with latest published versions
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4397 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4405 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4415 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4418 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4424 Update package index with latest published versions
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#4426 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4411 Recategorize azure-common to exist under the 'Other' label on github.io
  _data/releases/latest/python-packages.csv
Labels: Central-EngSys

#4441 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4443 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4448 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4452 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4458 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4461 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4462 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4466 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4468 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4474 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#4475 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4477 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#4480 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
Labels: auto-merge
