Repository Azure/azure-sdk, pull requests merged in 2023-01, with the labels that each got.

#5290 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/ios-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5300 Update package index with latest published versions
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#5302 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
Labels: auto-merge

#5304 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5325 Update package index with latest published versions
  _data/releases/latest/java-packages.csv
Labels: auto-merge

#5329 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5333 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#5334 Update package index with latest published versions
  _data/releases/latest/go-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5337 Update package index with latest published versions
  _data/releases/latest/cpp-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5339 Update package index with latest published versions
  _data/releases/latest/android-packages.csv
  _data/releases/latest/c-packages.csv
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#5343 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#5346 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
Labels: auto-merge

#5348 Update package index with latest published versions
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/java-packages.csv
  _data/releases/latest/js-packages.csv
  _data/releases/latest/python-packages.csv
Labels: auto-merge

#5381 Remove Azure Security KeyVault Common package from the C++ index since it never GA'd
  _data/releases/latest/cpp-packages.csv
Labels: KeyVault

#5377 Update latest embedded c release notes for January
  releases/2023-01/c.md
Labels: Azure.Core, IoT

#5380 Update embedded c release notes for August 2022 to back fill for 1.4.0-beta.1 release
  releases/2022-08/c.md
Labels: Azure.Core

#5406 Update index.md
  releases/2023-01/index.md
Labels: auto-merge

#4752 Add RequestContext to the guidelines around cancellation
  docs/dotnet/introduction.md
Labels: ArchBoard Guidelines
