Repository Azure/azure-sdk, pull requests merged in 2023-04, with the labels that each got.

#5914 Deprecating SDKs for Microsoft.StorSimple and Microsoft.HybridData
  _data/releases/latest/dotnet-packages.csv
  _data/releases/latest/go-packages.csv
  _data/releases/latest/js-packages.csv
Labels: SDK Deprecation

#5902 Azure Maps Elevation SDK Deprecation
  _data/releases/latest/java-packages.csv
Labels: SDK Deprecation

#5951 Update index.md
  releases/2023-04/index.md
Labels: auto-merge

#5959 Enable event processor for azure-sdk
  .github/event-processor.config
  .github/fabricbot.json
  .github/workflows/event-processor.yml
  .github/workflows/event.yml
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys
