Repository Azure/azure-sdk, pull requests merged in 2025-01, with the labels that each got.

#8373 Sync eng/common directory with azure-sdk-tools for PR 9580
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#8378 Sync eng/common directory with azure-sdk-tools for PR 9584
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#8400 Sync eng/common directory with azure-sdk-tools for PR 9614
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#8408 Sync eng/common directory with azure-sdk-tools for PR 9635
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#8359 Sync eng/common directory with azure-sdk-tools for PR 9529
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#8417 Sync eng/common directory with azure-sdk-tools for PR 9649
  eng/common/pipelines/templates/steps/save-package-properties.yml
  eng/common/scripts/Generate-PR-Diff.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#8422 Sync eng/common directory with azure-sdk-tools for PR 9577
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#8424 Sync eng/common directory with azure-sdk-tools for PR 9650
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#8413 Sync eng/common directory with azure-sdk-tools for PR 9601
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/pipelines/templates/steps/verify-readmes.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#8406 Sync eng/common directory with azure-sdk-tools for PR 9620
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#8425 Sync eng/common directory with azure-sdk-tools for PR 9658
  eng/common/scripts/Generate-PR-Diff.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#8438 Sync eng/common directory with azure-sdk-tools for PR 9656
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Remove-IssueLabel.ps1
Labels: EngSys, Central-EngSys

#8443 Sync eng/common directory with azure-sdk-tools for PR 9670
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#8294 Update adp_mgmt_namespace_review.md
  .github/ISSUE_TEMPLATE/adp_mgmt_namespace_review.md
Labels: no-recent-activity

#8444 Sync eng/common directory with azure-sdk-tools for PR 9681
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#8441 Sync eng/common directory with azure-sdk-tools for PR 9687
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#8452 Sync eng/common directory with azure-sdk-tools for PR 9699
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#8454 Sync eng/common directory with azure-sdk-tools for PR 9700
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#8437 Updated Support, EOLDate, and Migration Guides for Java libraries
  _data/releases/latest/java-packages.csv
Labels: Cognitive Services, Cognitive - Custom Vision, Cognitive - Face, Cognitive - LUIS, Cognitive - QnA Maker

#8458 Sync eng/common directory with azure-sdk-tools for PR 9724
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#8457 Sync eng/common directory with azure-sdk-tools for PR 9732
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys
